CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    identification VARCHAR(30) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT chk_persons_gender CHECK (gender IN ('MALE', 'FEMALE'))
);

CREATE TABLE customers (
    id BIGINT PRIMARY KEY,
    client_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_customers_persons FOREIGN KEY (id) REFERENCES persons (id) ON DELETE CASCADE
);

CREATE EXTENSION IF NOT EXISTS pgcrypto;

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Jose Lema', 'MALE', 34, '1723434343', 'Otavalo sn y principal', '098254785')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'joselema', crypt('1234', gen_salt('bf', 10)), TRUE FROM inserted_person;

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Marianela Montalvo', 'FEMALE', 28, '1723434344', 'Amazonas y NNUU', '097548965')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'marianela', crypt('5678', gen_salt('bf', 10)), TRUE FROM inserted_person;

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Juan Osorio', 'MALE', 32, '1723434345', '13 junio y Equinoccial', '098874587')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'juanosorio', crypt('1245', gen_salt('bf', 10)), TRUE FROM inserted_person;
