CREATE TABLE persons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    gender VARCHAR(20) NOT NULL,
    age INTEGER NOT NULL,
    identification VARCHAR(30) NOT NULL UNIQUE,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL
);

CREATE TABLE customers (
    id BIGINT PRIMARY KEY,
    client_id VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status BOOLEAN NOT NULL,
    CONSTRAINT fk_customers_persons FOREIGN KEY (id) REFERENCES persons (id) ON DELETE CASCADE
);

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Jose Lema', 'MALE', 34, '1723434343', 'Otavalo sn y principal', '098254785')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'joselema', '{noop}1234', TRUE FROM inserted_person;

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Marianela Montalvo', 'FEMALE', 28, '1723434344', 'Amazonas y NNUU', '097548965')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'mari', '{noop}5678', TRUE FROM inserted_person;

WITH inserted_person AS (
    INSERT INTO persons (name, gender, age, identification, address, phone)
    VALUES ('Juan Osorio', 'MALE', 32, '1723434345', '13 junio y Equinoccial', '098874587')
    RETURNING id
)
INSERT INTO customers (id, client_id, password, status)
SELECT id, 'juanito', '{noop}1245', TRUE FROM inserted_person;
